// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package cn.elmi.grpc.example.hello;

public final class GrpcHello {
    private GrpcHello() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_hello_HelloRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_hello_HelloRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_hello_HelloResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_hello_HelloResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\013Hello.proto\022\005hello\" \n\014HelloRequest\022\020\n\010" +
                        "question\030\001 \001(\t\"\037\n\rHelloResponse\022\016\n\006answe" +
                        "r\030\001 \001(\t2;\n\005Hello\0222\n\003say\022\023.hello.HelloReq" +
                        "uest\032\024.hello.HelloResponse\"\000B)\n\032cn.elmi." +
                        "grpc.example.helloB\tGrpcHelloP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_hello_HelloRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_hello_HelloRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_hello_HelloRequest_descriptor,
                new java.lang.String[]{"Question",});
        internal_static_hello_HelloResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_hello_HelloResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_hello_HelloResponse_descriptor,
                new java.lang.String[]{"Answer",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
