// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package cn.elmi.grpc.example.hello;

public interface HelloRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:hello.HelloRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string question = 1;</code>
     */
    java.lang.String getQuestion();

    /**
     * <code>string question = 1;</code>
     */
    com.google.protobuf.ByteString
    getQuestionBytes();
}
