// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Hello.proto

package cn.elmi.grpc.example.hello;

public interface HelloResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:hello.HelloResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string answer = 1;</code>
     */
    java.lang.String getAnswer();

    /**
     * <code>string answer = 1;</code>
     */
    com.google.protobuf.ByteString
    getAnswerBytes();
}
