spring.profiles.include: cache

grpc:
  server:
    name: example-server
    port: 10100
    registEtcd: true
  interceptors:
    #- cn.elmi.example.interceptor.BusinessInterceptor // 业务处理拦截器
    - cn.elmi.grpc.server.interceptor.TraceInterceptor // 日志追踪拦截器
    - cn.elmi.grpc.server.interceptor.AuthorizationInterceptor // 添加授权拦截器
    #- cn.elmi.example.interceptor.TokenInterceptor // 添加认证拦截器
    - cn.elmi.grpc.server.interceptor.CountInterceptor // 计数拦截器必须是最后一个添加的拦截器
  security:
    tls: true
    cert: certs/server.cer
    key: certs/server.key

etcd:
  retryTimes: 1
  beforeRetryTime: 300
  uris:
    - http://127.0.0.1:2379
  discovery:
    ttl: 10
    heartbeat: 5000

spring.cloud.etcd.discovery.heartbeat: 5000
spring.data.mongodb.uri: mongodb://127.0.0.1:27017/microservice
spring.output.ansi.enabled: ALWAYS
