// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OAuth.proto

package cn.elmi.grpc.example.oauth;

public final class GrpcOAuth {
    private GrpcOAuth() {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistryLite registry) {
    }

    public static void registerAllExtensions(
            com.google.protobuf.ExtensionRegistry registry) {
        registerAllExtensions(
                (com.google.protobuf.ExtensionRegistryLite) registry);
    }

    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_oauth_OAuthRequest_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_oauth_OAuthRequest_fieldAccessorTable;
    static final com.google.protobuf.Descriptors.Descriptor
            internal_static_oauth_OAuthResponse_descriptor;
    static final
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internal_static_oauth_OAuthResponse_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor
    getDescriptor() {
        return descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor
            descriptor;

    static {
        java.lang.String[] descriptorData = {
                "\n\013OAuth.proto\022\005oauth\"\213\001\n\014OAuthRequest\022\021\n" +
                        "\tgrantType\030\001 \001(\t\022\020\n\010clientId\030\002 \001(\t\022\024\n\014cl" +
                        "ientSecret\030\003 \001(\t\022\r\n\005scope\030\004 \001(\t\022\r\n\005token" +
                        "\030\005 \001(\t\022\020\n\010userName\030\006 \001(\t\022\020\n\010password\030\007 \001" +
                        "(\t\"C\n\rOAuthResponse\022\023\n\013accessToken\030\001 \001(\t" +
                        "\022\014\n\004type\030\002 \001(\t\022\017\n\007expired\030\003 \001(\0032F\n\005OAuth" +
                        "\022=\n\016getAccessToken\022\023.oauth.OAuthRequest\032" +
                        "\024.oauth.OAuthResponse\"\000B)\n\032cn.elmi.grpc." +
                        "example.oauthB\tGrpcOAuthP\001b\006proto3"
        };
        com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
                new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
                    public com.google.protobuf.ExtensionRegistry assignDescriptors(
                            com.google.protobuf.Descriptors.FileDescriptor root) {
                        descriptor = root;
                        return null;
                    }
                };
        com.google.protobuf.Descriptors.FileDescriptor
                .internalBuildGeneratedFileFrom(descriptorData,
                        new com.google.protobuf.Descriptors.FileDescriptor[]{
                        }, assigner);
        internal_static_oauth_OAuthRequest_descriptor =
                getDescriptor().getMessageTypes().get(0);
        internal_static_oauth_OAuthRequest_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_oauth_OAuthRequest_descriptor,
                new java.lang.String[]{"GrantType", "ClientId", "ClientSecret", "Scope", "Token", "UserName", "Password",});
        internal_static_oauth_OAuthResponse_descriptor =
                getDescriptor().getMessageTypes().get(1);
        internal_static_oauth_OAuthResponse_fieldAccessorTable = new
                com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
                internal_static_oauth_OAuthResponse_descriptor,
                new java.lang.String[]{"AccessToken", "Type", "Expired",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
