// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OAuth.proto

package cn.elmi.grpc.example.oauth;

public interface OAuthRequestOrBuilder extends
        // @@protoc_insertion_point(interface_extends:oauth.OAuthRequest)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * * 授权类型
     * </pre>
     *
     * <code>string grantType = 1;</code>
     */
    java.lang.String getGrantType();

    /**
     * <pre>
     * * 授权类型
     * </pre>
     *
     * <code>string grantType = 1;</code>
     */
    com.google.protobuf.ByteString
    getGrantTypeBytes();

    /**
     * <pre>
     * * clientId
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    java.lang.String getClientId();

    /**
     * <pre>
     * * clientId
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    com.google.protobuf.ByteString
    getClientIdBytes();

    /**
     * <pre>
     * * 私钥
     * </pre>
     *
     * <code>string clientSecret = 3;</code>
     */
    java.lang.String getClientSecret();

    /**
     * <pre>
     * * 私钥
     * </pre>
     *
     * <code>string clientSecret = 3;</code>
     */
    com.google.protobuf.ByteString
    getClientSecretBytes();

    /**
     * <pre>
     * * 范围
     * </pre>
     *
     * <code>string scope = 4;</code>
     */
    java.lang.String getScope();

    /**
     * <pre>
     * * 范围
     * </pre>
     *
     * <code>string scope = 4;</code>
     */
    com.google.protobuf.ByteString
    getScopeBytes();

    /**
     * <pre>
     * * 签名
     * </pre>
     *
     * <code>string token = 5;</code>
     */
    java.lang.String getToken();

    /**
     * <pre>
     * * 签名
     * </pre>
     *
     * <code>string token = 5;</code>
     */
    com.google.protobuf.ByteString
    getTokenBytes();

    /**
     * <pre>
     * * 用户名
     * </pre>
     *
     * <code>string userName = 6;</code>
     */
    java.lang.String getUserName();

    /**
     * <pre>
     * * 用户名
     * </pre>
     *
     * <code>string userName = 6;</code>
     */
    com.google.protobuf.ByteString
    getUserNameBytes();

    /**
     * <pre>
     * * 密码
     * </pre>
     *
     * <code>string password = 7;</code>
     */
    java.lang.String getPassword();

    /**
     * <pre>
     * * 密码
     * </pre>
     *
     * <code>string password = 7;</code>
     */
    com.google.protobuf.ByteString
    getPasswordBytes();
}
