// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OAuth.proto

package cn.elmi.grpc.example.oauth;

public interface OAuthResponseOrBuilder extends
        // @@protoc_insertion_point(interface_extends:oauth.OAuthResponse)
        com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * * 访问签名
     * </pre>
     *
     * <code>string accessToken = 1;</code>
     */
    java.lang.String getAccessToken();

    /**
     * <pre>
     * * 访问签名
     * </pre>
     *
     * <code>string accessToken = 1;</code>
     */
    com.google.protobuf.ByteString
    getAccessTokenBytes();

    /**
     * <pre>
     * * 签名类型
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    java.lang.String getType();

    /**
     * <pre>
     * * 签名类型
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    com.google.protobuf.ByteString
    getTypeBytes();

    /**
     * <pre>
     * * 过期时间/毫秒
     * </pre>
     *
     * <code>int64 expired = 3;</code>
     */
    long getExpired();
}
