// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OAuth.proto

package cn.elmi.grpc.example.oauth;

/**
 * Protobuf type {@code oauth.OAuthRequest}
 */
public final class OAuthRequest extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:oauth.OAuthRequest)
        OAuthRequestOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use OAuthRequest.newBuilder() to construct.
    private OAuthRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private OAuthRequest() {
        grantType_ = "";
        clientId_ = "";
        clientSecret_ = "";
        scope_ = "";
        token_ = "";
        userName_ = "";
        password_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private OAuthRequest(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        grantType_ = s;
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        clientId_ = s;
                        break;
                    }
                    case 26: {
                        java.lang.String s = input.readStringRequireUtf8();

                        clientSecret_ = s;
                        break;
                    }
                    case 34: {
                        java.lang.String s = input.readStringRequireUtf8();

                        scope_ = s;
                        break;
                    }
                    case 42: {
                        java.lang.String s = input.readStringRequireUtf8();

                        token_ = s;
                        break;
                    }
                    case 50: {
                        java.lang.String s = input.readStringRequireUtf8();

                        userName_ = s;
                        break;
                    }
                    case 58: {
                        java.lang.String s = input.readStringRequireUtf8();

                        password_ = s;
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.elmi.grpc.example.oauth.GrpcOAuth.internal_static_oauth_OAuthRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.elmi.grpc.example.oauth.GrpcOAuth.internal_static_oauth_OAuthRequest_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.elmi.grpc.example.oauth.OAuthRequest.class, cn.elmi.grpc.example.oauth.OAuthRequest.Builder.class);
    }

    public static final int GRANTTYPE_FIELD_NUMBER = 1;
    private volatile java.lang.Object grantType_;

    /**
     * <pre>
     * * 授权类型
     * </pre>
     *
     * <code>string grantType = 1;</code>
     */
    public java.lang.String getGrantType() {
        java.lang.Object ref = grantType_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            grantType_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * * 授权类型
     * </pre>
     *
     * <code>string grantType = 1;</code>
     */
    public com.google.protobuf.ByteString
    getGrantTypeBytes() {
        java.lang.Object ref = grantType_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            grantType_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CLIENTID_FIELD_NUMBER = 2;
    private volatile java.lang.Object clientId_;

    /**
     * <pre>
     * * clientId
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public java.lang.String getClientId() {
        java.lang.Object ref = clientId_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            clientId_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * * clientId
     * </pre>
     *
     * <code>string clientId = 2;</code>
     */
    public com.google.protobuf.ByteString
    getClientIdBytes() {
        java.lang.Object ref = clientId_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            clientId_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int CLIENTSECRET_FIELD_NUMBER = 3;
    private volatile java.lang.Object clientSecret_;

    /**
     * <pre>
     * * 私钥
     * </pre>
     *
     * <code>string clientSecret = 3;</code>
     */
    public java.lang.String getClientSecret() {
        java.lang.Object ref = clientSecret_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            clientSecret_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * * 私钥
     * </pre>
     *
     * <code>string clientSecret = 3;</code>
     */
    public com.google.protobuf.ByteString
    getClientSecretBytes() {
        java.lang.Object ref = clientSecret_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            clientSecret_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int SCOPE_FIELD_NUMBER = 4;
    private volatile java.lang.Object scope_;

    /**
     * <pre>
     * * 范围
     * </pre>
     *
     * <code>string scope = 4;</code>
     */
    public java.lang.String getScope() {
        java.lang.Object ref = scope_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            scope_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * * 范围
     * </pre>
     *
     * <code>string scope = 4;</code>
     */
    public com.google.protobuf.ByteString
    getScopeBytes() {
        java.lang.Object ref = scope_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            scope_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int TOKEN_FIELD_NUMBER = 5;
    private volatile java.lang.Object token_;

    /**
     * <pre>
     * * 签名
     * </pre>
     *
     * <code>string token = 5;</code>
     */
    public java.lang.String getToken() {
        java.lang.Object ref = token_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            token_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * * 签名
     * </pre>
     *
     * <code>string token = 5;</code>
     */
    public com.google.protobuf.ByteString
    getTokenBytes() {
        java.lang.Object ref = token_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            token_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int USERNAME_FIELD_NUMBER = 6;
    private volatile java.lang.Object userName_;

    /**
     * <pre>
     * * 用户名
     * </pre>
     *
     * <code>string userName = 6;</code>
     */
    public java.lang.String getUserName() {
        java.lang.Object ref = userName_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            userName_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * * 用户名
     * </pre>
     *
     * <code>string userName = 6;</code>
     */
    public com.google.protobuf.ByteString
    getUserNameBytes() {
        java.lang.Object ref = userName_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            userName_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int PASSWORD_FIELD_NUMBER = 7;
    private volatile java.lang.Object password_;

    /**
     * <pre>
     * * 密码
     * </pre>
     *
     * <code>string password = 7;</code>
     */
    public java.lang.String getPassword() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            password_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * * 密码
     * </pre>
     *
     * <code>string password = 7;</code>
     */
    public com.google.protobuf.ByteString
    getPasswordBytes() {
        java.lang.Object ref = password_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            password_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getGrantTypeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, grantType_);
        }
        if (!getClientIdBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, clientId_);
        }
        if (!getClientSecretBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 3, clientSecret_);
        }
        if (!getScopeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 4, scope_);
        }
        if (!getTokenBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 5, token_);
        }
        if (!getUserNameBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 6, userName_);
        }
        if (!getPasswordBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 7, password_);
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getGrantTypeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, grantType_);
        }
        if (!getClientIdBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, clientId_);
        }
        if (!getClientSecretBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, clientSecret_);
        }
        if (!getScopeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, scope_);
        }
        if (!getTokenBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, token_);
        }
        if (!getUserNameBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(6, userName_);
        }
        if (!getPasswordBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(7, password_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cn.elmi.grpc.example.oauth.OAuthRequest)) {
            return super.equals(obj);
        }
        cn.elmi.grpc.example.oauth.OAuthRequest other = (cn.elmi.grpc.example.oauth.OAuthRequest) obj;

        boolean result = true;
        result = result && getGrantType()
                .equals(other.getGrantType());
        result = result && getClientId()
                .equals(other.getClientId());
        result = result && getClientSecret()
                .equals(other.getClientSecret());
        result = result && getScope()
                .equals(other.getScope());
        result = result && getToken()
                .equals(other.getToken());
        result = result && getUserName()
                .equals(other.getUserName());
        result = result && getPassword()
                .equals(other.getPassword());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + GRANTTYPE_FIELD_NUMBER;
        hash = (53 * hash) + getGrantType().hashCode();
        hash = (37 * hash) + CLIENTID_FIELD_NUMBER;
        hash = (53 * hash) + getClientId().hashCode();
        hash = (37 * hash) + CLIENTSECRET_FIELD_NUMBER;
        hash = (53 * hash) + getClientSecret().hashCode();
        hash = (37 * hash) + SCOPE_FIELD_NUMBER;
        hash = (53 * hash) + getScope().hashCode();
        hash = (37 * hash) + TOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getToken().hashCode();
        hash = (37 * hash) + USERNAME_FIELD_NUMBER;
        hash = (53 * hash) + getUserName().hashCode();
        hash = (37 * hash) + PASSWORD_FIELD_NUMBER;
        hash = (53 * hash) + getPassword().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(cn.elmi.grpc.example.oauth.OAuthRequest prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code oauth.OAuthRequest}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:oauth.OAuthRequest)
            cn.elmi.grpc.example.oauth.OAuthRequestOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.elmi.grpc.example.oauth.GrpcOAuth.internal_static_oauth_OAuthRequest_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.elmi.grpc.example.oauth.GrpcOAuth.internal_static_oauth_OAuthRequest_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.elmi.grpc.example.oauth.OAuthRequest.class, cn.elmi.grpc.example.oauth.OAuthRequest.Builder.class);
        }

        // Construct using cn.elmi.grpc.example.oauth.OAuthRequest.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            grantType_ = "";

            clientId_ = "";

            clientSecret_ = "";

            scope_ = "";

            token_ = "";

            userName_ = "";

            password_ = "";

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cn.elmi.grpc.example.oauth.GrpcOAuth.internal_static_oauth_OAuthRequest_descriptor;
        }

        public cn.elmi.grpc.example.oauth.OAuthRequest getDefaultInstanceForType() {
            return cn.elmi.grpc.example.oauth.OAuthRequest.getDefaultInstance();
        }

        public cn.elmi.grpc.example.oauth.OAuthRequest build() {
            cn.elmi.grpc.example.oauth.OAuthRequest result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public cn.elmi.grpc.example.oauth.OAuthRequest buildPartial() {
            cn.elmi.grpc.example.oauth.OAuthRequest result = new cn.elmi.grpc.example.oauth.OAuthRequest(this);
            result.grantType_ = grantType_;
            result.clientId_ = clientId_;
            result.clientSecret_ = clientSecret_;
            result.scope_ = scope_;
            result.token_ = token_;
            result.userName_ = userName_;
            result.password_ = password_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.elmi.grpc.example.oauth.OAuthRequest) {
                return mergeFrom((cn.elmi.grpc.example.oauth.OAuthRequest) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cn.elmi.grpc.example.oauth.OAuthRequest other) {
            if (other == cn.elmi.grpc.example.oauth.OAuthRequest.getDefaultInstance()) return this;
            if (!other.getGrantType().isEmpty()) {
                grantType_ = other.grantType_;
                onChanged();
            }
            if (!other.getClientId().isEmpty()) {
                clientId_ = other.clientId_;
                onChanged();
            }
            if (!other.getClientSecret().isEmpty()) {
                clientSecret_ = other.clientSecret_;
                onChanged();
            }
            if (!other.getScope().isEmpty()) {
                scope_ = other.scope_;
                onChanged();
            }
            if (!other.getToken().isEmpty()) {
                token_ = other.token_;
                onChanged();
            }
            if (!other.getUserName().isEmpty()) {
                userName_ = other.userName_;
                onChanged();
            }
            if (!other.getPassword().isEmpty()) {
                password_ = other.password_;
                onChanged();
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            cn.elmi.grpc.example.oauth.OAuthRequest parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (cn.elmi.grpc.example.oauth.OAuthRequest) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private java.lang.Object grantType_ = "";

        /**
         * <pre>
         * * 授权类型
         * </pre>
         *
         * <code>string grantType = 1;</code>
         */
        public java.lang.String getGrantType() {
            java.lang.Object ref = grantType_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                grantType_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * * 授权类型
         * </pre>
         *
         * <code>string grantType = 1;</code>
         */
        public com.google.protobuf.ByteString
        getGrantTypeBytes() {
            java.lang.Object ref = grantType_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                grantType_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * * 授权类型
         * </pre>
         *
         * <code>string grantType = 1;</code>
         */
        public Builder setGrantType(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            grantType_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 授权类型
         * </pre>
         *
         * <code>string grantType = 1;</code>
         */
        public Builder clearGrantType() {

            grantType_ = getDefaultInstance().getGrantType();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 授权类型
         * </pre>
         *
         * <code>string grantType = 1;</code>
         */
        public Builder setGrantTypeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            grantType_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object clientId_ = "";

        /**
         * <pre>
         * * clientId
         * </pre>
         *
         * <code>string clientId = 2;</code>
         */
        public java.lang.String getClientId() {
            java.lang.Object ref = clientId_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                clientId_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * * clientId
         * </pre>
         *
         * <code>string clientId = 2;</code>
         */
        public com.google.protobuf.ByteString
        getClientIdBytes() {
            java.lang.Object ref = clientId_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                clientId_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * * clientId
         * </pre>
         *
         * <code>string clientId = 2;</code>
         */
        public Builder setClientId(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            clientId_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * clientId
         * </pre>
         *
         * <code>string clientId = 2;</code>
         */
        public Builder clearClientId() {

            clientId_ = getDefaultInstance().getClientId();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * clientId
         * </pre>
         *
         * <code>string clientId = 2;</code>
         */
        public Builder setClientIdBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            clientId_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object clientSecret_ = "";

        /**
         * <pre>
         * * 私钥
         * </pre>
         *
         * <code>string clientSecret = 3;</code>
         */
        public java.lang.String getClientSecret() {
            java.lang.Object ref = clientSecret_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                clientSecret_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * * 私钥
         * </pre>
         *
         * <code>string clientSecret = 3;</code>
         */
        public com.google.protobuf.ByteString
        getClientSecretBytes() {
            java.lang.Object ref = clientSecret_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                clientSecret_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * * 私钥
         * </pre>
         *
         * <code>string clientSecret = 3;</code>
         */
        public Builder setClientSecret(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            clientSecret_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 私钥
         * </pre>
         *
         * <code>string clientSecret = 3;</code>
         */
        public Builder clearClientSecret() {

            clientSecret_ = getDefaultInstance().getClientSecret();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 私钥
         * </pre>
         *
         * <code>string clientSecret = 3;</code>
         */
        public Builder setClientSecretBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            clientSecret_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object scope_ = "";

        /**
         * <pre>
         * * 范围
         * </pre>
         *
         * <code>string scope = 4;</code>
         */
        public java.lang.String getScope() {
            java.lang.Object ref = scope_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                scope_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * * 范围
         * </pre>
         *
         * <code>string scope = 4;</code>
         */
        public com.google.protobuf.ByteString
        getScopeBytes() {
            java.lang.Object ref = scope_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                scope_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * * 范围
         * </pre>
         *
         * <code>string scope = 4;</code>
         */
        public Builder setScope(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            scope_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 范围
         * </pre>
         *
         * <code>string scope = 4;</code>
         */
        public Builder clearScope() {

            scope_ = getDefaultInstance().getScope();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 范围
         * </pre>
         *
         * <code>string scope = 4;</code>
         */
        public Builder setScopeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            scope_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object token_ = "";

        /**
         * <pre>
         * * 签名
         * </pre>
         *
         * <code>string token = 5;</code>
         */
        public java.lang.String getToken() {
            java.lang.Object ref = token_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                token_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * * 签名
         * </pre>
         *
         * <code>string token = 5;</code>
         */
        public com.google.protobuf.ByteString
        getTokenBytes() {
            java.lang.Object ref = token_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                token_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * * 签名
         * </pre>
         *
         * <code>string token = 5;</code>
         */
        public Builder setToken(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            token_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 签名
         * </pre>
         *
         * <code>string token = 5;</code>
         */
        public Builder clearToken() {

            token_ = getDefaultInstance().getToken();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 签名
         * </pre>
         *
         * <code>string token = 5;</code>
         */
        public Builder setTokenBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            token_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object userName_ = "";

        /**
         * <pre>
         * * 用户名
         * </pre>
         *
         * <code>string userName = 6;</code>
         */
        public java.lang.String getUserName() {
            java.lang.Object ref = userName_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                userName_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * * 用户名
         * </pre>
         *
         * <code>string userName = 6;</code>
         */
        public com.google.protobuf.ByteString
        getUserNameBytes() {
            java.lang.Object ref = userName_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                userName_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * * 用户名
         * </pre>
         *
         * <code>string userName = 6;</code>
         */
        public Builder setUserName(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            userName_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 用户名
         * </pre>
         *
         * <code>string userName = 6;</code>
         */
        public Builder clearUserName() {

            userName_ = getDefaultInstance().getUserName();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 用户名
         * </pre>
         *
         * <code>string userName = 6;</code>
         */
        public Builder setUserNameBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            userName_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object password_ = "";

        /**
         * <pre>
         * * 密码
         * </pre>
         *
         * <code>string password = 7;</code>
         */
        public java.lang.String getPassword() {
            java.lang.Object ref = password_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                password_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * * 密码
         * </pre>
         *
         * <code>string password = 7;</code>
         */
        public com.google.protobuf.ByteString
        getPasswordBytes() {
            java.lang.Object ref = password_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                password_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * * 密码
         * </pre>
         *
         * <code>string password = 7;</code>
         */
        public Builder setPassword(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            password_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 密码
         * </pre>
         *
         * <code>string password = 7;</code>
         */
        public Builder clearPassword() {

            password_ = getDefaultInstance().getPassword();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 密码
         * </pre>
         *
         * <code>string password = 7;</code>
         */
        public Builder setPasswordBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            password_ = value;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:oauth.OAuthRequest)
    }

    // @@protoc_insertion_point(class_scope:oauth.OAuthRequest)
    private static final cn.elmi.grpc.example.oauth.OAuthRequest DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new cn.elmi.grpc.example.oauth.OAuthRequest();
    }

    public static cn.elmi.grpc.example.oauth.OAuthRequest getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OAuthRequest>
            PARSER = new com.google.protobuf.AbstractParser<OAuthRequest>() {
        public OAuthRequest parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new OAuthRequest(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<OAuthRequest> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OAuthRequest> getParserForType() {
        return PARSER;
    }

    public cn.elmi.grpc.example.oauth.OAuthRequest getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

