// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: OAuth.proto

package cn.elmi.grpc.example.oauth;

/**
 * Protobuf type {@code oauth.OAuthResponse}
 */
public final class OAuthResponse extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:oauth.OAuthResponse)
        OAuthResponseOrBuilder {
    private static final long serialVersionUID = 0L;

    // Use OAuthResponse.newBuilder() to construct.
    private OAuthResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
    }

    private OAuthResponse() {
        accessToken_ = "";
        type_ = "";
        expired_ = 0L;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
        return this.unknownFields;
    }

    private OAuthResponse(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
            throw new java.lang.NullPointerException();
        }
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
                com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
            boolean done = false;
            while (!done) {
                int tag = input.readTag();
                switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!parseUnknownFieldProto3(
                                input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 10: {
                        java.lang.String s = input.readStringRequireUtf8();

                        accessToken_ = s;
                        break;
                    }
                    case 18: {
                        java.lang.String s = input.readStringRequireUtf8();

                        type_ = s;
                        break;
                    }
                    case 24: {

                        expired_ = input.readInt64();
                        break;
                    }
                }
            }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
            throw new com.google.protobuf.InvalidProtocolBufferException(
                    e).setUnfinishedMessage(this);
        } finally {
            this.unknownFields = unknownFields.build();
            makeExtensionsImmutable();
        }
    }

    public static final com.google.protobuf.Descriptors.Descriptor
    getDescriptor() {
        return cn.elmi.grpc.example.oauth.GrpcOAuth.internal_static_oauth_OAuthResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
    internalGetFieldAccessorTable() {
        return cn.elmi.grpc.example.oauth.GrpcOAuth.internal_static_oauth_OAuthResponse_fieldAccessorTable
                .ensureFieldAccessorsInitialized(
                        cn.elmi.grpc.example.oauth.OAuthResponse.class, cn.elmi.grpc.example.oauth.OAuthResponse.Builder.class);
    }

    public static final int ACCESSTOKEN_FIELD_NUMBER = 1;
    private volatile java.lang.Object accessToken_;

    /**
     * <pre>
     * * 访问签名
     * </pre>
     *
     * <code>string accessToken = 1;</code>
     */
    public java.lang.String getAccessToken() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            accessToken_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * * 访问签名
     * </pre>
     *
     * <code>string accessToken = 1;</code>
     */
    public com.google.protobuf.ByteString
    getAccessTokenBytes() {
        java.lang.Object ref = accessToken_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            accessToken_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int TYPE_FIELD_NUMBER = 2;
    private volatile java.lang.Object type_;

    /**
     * <pre>
     * * 签名类型
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    public java.lang.String getType() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
            return (java.lang.String) ref;
        } else {
            com.google.protobuf.ByteString bs =
                    (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            type_ = s;
            return s;
        }
    }

    /**
     * <pre>
     * * 签名类型
     * </pre>
     *
     * <code>string type = 2;</code>
     */
    public com.google.protobuf.ByteString
    getTypeBytes() {
        java.lang.Object ref = type_;
        if (ref instanceof java.lang.String) {
            com.google.protobuf.ByteString b =
                    com.google.protobuf.ByteString.copyFromUtf8(
                            (java.lang.String) ref);
            type_ = b;
            return b;
        } else {
            return (com.google.protobuf.ByteString) ref;
        }
    }

    public static final int EXPIRED_FIELD_NUMBER = 3;
    private long expired_;

    /**
     * <pre>
     * * 过期时间/毫秒
     * </pre>
     *
     * <code>int64 expired = 3;</code>
     */
    public long getExpired() {
        return expired_;
    }

    private byte memoizedIsInitialized = -1;

    public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
            throws java.io.IOException {
        if (!getAccessTokenBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 1, accessToken_);
        }
        if (!getTypeBytes().isEmpty()) {
            com.google.protobuf.GeneratedMessageV3.writeString(output, 2, type_);
        }
        if (expired_ != 0L) {
            output.writeInt64(3, expired_);
        }
        unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getAccessTokenBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, accessToken_);
        }
        if (!getTypeBytes().isEmpty()) {
            size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, type_);
        }
        if (expired_ != 0L) {
            size += com.google.protobuf.CodedOutputStream
                    .computeInt64Size(3, expired_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
            return true;
        }
        if (!(obj instanceof cn.elmi.grpc.example.oauth.OAuthResponse)) {
            return super.equals(obj);
        }
        cn.elmi.grpc.example.oauth.OAuthResponse other = (cn.elmi.grpc.example.oauth.OAuthResponse) obj;

        boolean result = true;
        result = result && getAccessToken()
                .equals(other.getAccessToken());
        result = result && getType()
                .equals(other.getType());
        result = result && (getExpired()
                == other.getExpired());
        result = result && unknownFields.equals(other.unknownFields);
        return result;
    }

    @java.lang.Override
    public int hashCode() {
        if (memoizedHashCode != 0) {
            return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + ACCESSTOKEN_FIELD_NUMBER;
        hash = (53 * hash) + getAccessToken().hashCode();
        hash = (37 * hash) + TYPE_FIELD_NUMBER;
        hash = (53 * hash) + getType().hashCode();
        hash = (37 * hash) + EXPIRED_FIELD_NUMBER;
        hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
                getExpired());
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse parseFrom(
            java.nio.ByteBuffer data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse parseFrom(
            java.nio.ByteBuffer data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse parseFrom(
            com.google.protobuf.ByteString data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse parseFrom(
            com.google.protobuf.ByteString data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse parseFrom(byte[] data)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse parseFrom(
            byte[] data,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse parseFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse parseFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse parseDelimitedFrom(java.io.InputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input);
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse parseDelimitedFrom(
            java.io.InputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse parseFrom(
            com.google.protobuf.CodedInputStream input)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input);
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse parseFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
                .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() {
        return newBuilder();
    }

    public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
    }

    public static Builder newBuilder(cn.elmi.grpc.example.oauth.OAuthResponse prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }

    public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
                ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
    }

    /**
     * Protobuf type {@code oauth.OAuthResponse}
     */
    public static final class Builder extends
            com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
            // @@protoc_insertion_point(builder_implements:oauth.OAuthResponse)
            cn.elmi.grpc.example.oauth.OAuthResponseOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
            return cn.elmi.grpc.example.oauth.GrpcOAuth.internal_static_oauth_OAuthResponse_descriptor;
        }

        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
            return cn.elmi.grpc.example.oauth.GrpcOAuth.internal_static_oauth_OAuthResponse_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(
                            cn.elmi.grpc.example.oauth.OAuthResponse.class, cn.elmi.grpc.example.oauth.OAuthResponse.Builder.class);
        }

        // Construct using cn.elmi.grpc.example.oauth.OAuthResponse.newBuilder()
        private Builder() {
            maybeForceBuilderInitialization();
        }

        private Builder(
                com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
            super(parent);
            maybeForceBuilderInitialization();
        }

        private void maybeForceBuilderInitialization() {
            if (com.google.protobuf.GeneratedMessageV3
                    .alwaysUseFieldBuilders) {
            }
        }

        public Builder clear() {
            super.clear();
            accessToken_ = "";

            type_ = "";

            expired_ = 0L;

            return this;
        }

        public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
            return cn.elmi.grpc.example.oauth.GrpcOAuth.internal_static_oauth_OAuthResponse_descriptor;
        }

        public cn.elmi.grpc.example.oauth.OAuthResponse getDefaultInstanceForType() {
            return cn.elmi.grpc.example.oauth.OAuthResponse.getDefaultInstance();
        }

        public cn.elmi.grpc.example.oauth.OAuthResponse build() {
            cn.elmi.grpc.example.oauth.OAuthResponse result = buildPartial();
            if (!result.isInitialized()) {
                throw newUninitializedMessageException(result);
            }
            return result;
        }

        public cn.elmi.grpc.example.oauth.OAuthResponse buildPartial() {
            cn.elmi.grpc.example.oauth.OAuthResponse result = new cn.elmi.grpc.example.oauth.OAuthResponse(this);
            result.accessToken_ = accessToken_;
            result.type_ = type_;
            result.expired_ = expired_;
            onBuilt();
            return result;
        }

        public Builder clone() {
            return super.clone();
        }

        public Builder setField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.setField(field, value);
        }

        public Builder clearField(
                com.google.protobuf.Descriptors.FieldDescriptor field) {
            return super.clearField(field);
        }

        public Builder clearOneof(
                com.google.protobuf.Descriptors.OneofDescriptor oneof) {
            return super.clearOneof(oneof);
        }

        public Builder setRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                int index, java.lang.Object value) {
            return super.setRepeatedField(field, index, value);
        }

        public Builder addRepeatedField(
                com.google.protobuf.Descriptors.FieldDescriptor field,
                java.lang.Object value) {
            return super.addRepeatedField(field, value);
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
            if (other instanceof cn.elmi.grpc.example.oauth.OAuthResponse) {
                return mergeFrom((cn.elmi.grpc.example.oauth.OAuthResponse) other);
            } else {
                super.mergeFrom(other);
                return this;
            }
        }

        public Builder mergeFrom(cn.elmi.grpc.example.oauth.OAuthResponse other) {
            if (other == cn.elmi.grpc.example.oauth.OAuthResponse.getDefaultInstance()) return this;
            if (!other.getAccessToken().isEmpty()) {
                accessToken_ = other.accessToken_;
                onChanged();
            }
            if (!other.getType().isEmpty()) {
                type_ = other.type_;
                onChanged();
            }
            if (other.getExpired() != 0L) {
                setExpired(other.getExpired());
            }
            this.mergeUnknownFields(other.unknownFields);
            onChanged();
            return this;
        }

        public final boolean isInitialized() {
            return true;
        }

        public Builder mergeFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws java.io.IOException {
            cn.elmi.grpc.example.oauth.OAuthResponse parsedMessage = null;
            try {
                parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
            } catch (com.google.protobuf.InvalidProtocolBufferException e) {
                parsedMessage = (cn.elmi.grpc.example.oauth.OAuthResponse) e.getUnfinishedMessage();
                throw e.unwrapIOException();
            } finally {
                if (parsedMessage != null) {
                    mergeFrom(parsedMessage);
                }
            }
            return this;
        }

        private java.lang.Object accessToken_ = "";

        /**
         * <pre>
         * * 访问签名
         * </pre>
         *
         * <code>string accessToken = 1;</code>
         */
        public java.lang.String getAccessToken() {
            java.lang.Object ref = accessToken_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                accessToken_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * * 访问签名
         * </pre>
         *
         * <code>string accessToken = 1;</code>
         */
        public com.google.protobuf.ByteString
        getAccessTokenBytes() {
            java.lang.Object ref = accessToken_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                accessToken_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * * 访问签名
         * </pre>
         *
         * <code>string accessToken = 1;</code>
         */
        public Builder setAccessToken(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            accessToken_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 访问签名
         * </pre>
         *
         * <code>string accessToken = 1;</code>
         */
        public Builder clearAccessToken() {

            accessToken_ = getDefaultInstance().getAccessToken();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 访问签名
         * </pre>
         *
         * <code>string accessToken = 1;</code>
         */
        public Builder setAccessTokenBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            accessToken_ = value;
            onChanged();
            return this;
        }

        private java.lang.Object type_ = "";

        /**
         * <pre>
         * * 签名类型
         * </pre>
         *
         * <code>string type = 2;</code>
         */
        public java.lang.String getType() {
            java.lang.Object ref = type_;
            if (!(ref instanceof java.lang.String)) {
                com.google.protobuf.ByteString bs =
                        (com.google.protobuf.ByteString) ref;
                java.lang.String s = bs.toStringUtf8();
                type_ = s;
                return s;
            } else {
                return (java.lang.String) ref;
            }
        }

        /**
         * <pre>
         * * 签名类型
         * </pre>
         *
         * <code>string type = 2;</code>
         */
        public com.google.protobuf.ByteString
        getTypeBytes() {
            java.lang.Object ref = type_;
            if (ref instanceof String) {
                com.google.protobuf.ByteString b =
                        com.google.protobuf.ByteString.copyFromUtf8(
                                (java.lang.String) ref);
                type_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        /**
         * <pre>
         * * 签名类型
         * </pre>
         *
         * <code>string type = 2;</code>
         */
        public Builder setType(
                java.lang.String value) {
            if (value == null) {
                throw new NullPointerException();
            }

            type_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 签名类型
         * </pre>
         *
         * <code>string type = 2;</code>
         */
        public Builder clearType() {

            type_ = getDefaultInstance().getType();
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 签名类型
         * </pre>
         *
         * <code>string type = 2;</code>
         */
        public Builder setTypeBytes(
                com.google.protobuf.ByteString value) {
            if (value == null) {
                throw new NullPointerException();
            }
            checkByteStringIsUtf8(value);

            type_ = value;
            onChanged();
            return this;
        }

        private long expired_;

        /**
         * <pre>
         * * 过期时间/毫秒
         * </pre>
         *
         * <code>int64 expired = 3;</code>
         */
        public long getExpired() {
            return expired_;
        }

        /**
         * <pre>
         * * 过期时间/毫秒
         * </pre>
         *
         * <code>int64 expired = 3;</code>
         */
        public Builder setExpired(long value) {

            expired_ = value;
            onChanged();
            return this;
        }

        /**
         * <pre>
         * * 过期时间/毫秒
         * </pre>
         *
         * <code>int64 expired = 3;</code>
         */
        public Builder clearExpired() {

            expired_ = 0L;
            onChanged();
            return this;
        }

        public final Builder setUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.setUnknownFieldsProto3(unknownFields);
        }

        public final Builder mergeUnknownFields(
                final com.google.protobuf.UnknownFieldSet unknownFields) {
            return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:oauth.OAuthResponse)
    }

    // @@protoc_insertion_point(class_scope:oauth.OAuthResponse)
    private static final cn.elmi.grpc.example.oauth.OAuthResponse DEFAULT_INSTANCE;

    static {
        DEFAULT_INSTANCE = new cn.elmi.grpc.example.oauth.OAuthResponse();
    }

    public static cn.elmi.grpc.example.oauth.OAuthResponse getDefaultInstance() {
        return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<OAuthResponse>
            PARSER = new com.google.protobuf.AbstractParser<OAuthResponse>() {
        public OAuthResponse parsePartialFrom(
                com.google.protobuf.CodedInputStream input,
                com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return new OAuthResponse(input, extensionRegistry);
        }
    };

    public static com.google.protobuf.Parser<OAuthResponse> parser() {
        return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<OAuthResponse> getParserForType() {
        return PARSER;
    }

    public cn.elmi.grpc.example.oauth.OAuthResponse getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
    }

}

